"""The `evolve` action for operators: synthesize against a spec the router emitted, certify, admit into the vault.

A spec names a case, a relocated formulation, the in-solver per-iteration budget on a device, and the set the operator
must project onto. The run is SkyDiscover with the in-solver evaluator (sky_eval_v3), seeded with the best certified
component the vault already has for that set, so rounds compound. Top programs are re-certified independently and
admitted as components with full provenance.
"""
from __future__ import annotations

import glob
import json
import os
import shutil
import subprocess
import sys
import time

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from vault import Vault

HERE = os.path.dirname(os.path.abspath(__file__))
SKY_PY = "/home/miria/skyenv/bin/python"
PY = "/home/miria/jaxenv2/bin/python"

PROMPT = """You write numerical kernels in JAX. Task: implement `project(v, lo, hi, a, b)`, the EXACT Euclidean projection
of v onto {{x : lo <= x <= hi, a'x = b}}, where lo, hi are float64 arrays (lo finite, hi may be +inf), a is an array whose
entries may have EITHER sign (none are zero), b is a scalar, and the set is non-empty. It must be jax.jit compatible
(static shapes, no Python if/while on traced values; jax.lax control flow is fine), float64, same shape as v.
SPECIFICATION (generated by the vault's cost model, checked automatically):
  (1) exactness: max |x - x_ref| / (1 + max|x_ref|) <= 1e-9 on randomized, mixed-sign, infinite-bound, small and large,
      degenerate and deployment inputs; x feasible. Feedback names any violated contract clause.
  (2) speed, measured IN THE SOLVER: on {device}, the relocated formulation of {case} (block n = {n_x}) must cost at most
      {budget_us:.1f} microseconds per iteration including this operator. The current best certified operator (the
      starting program) costs {current_us:.1f} microseconds per iteration there. Meeting the budget flips the solver's
      formulation decision for this instance.
Useful facts: x(mu) = clip(v - mu*a, lo, hi) and phi(mu) = a'x(mu) is piecewise linear and nonincreasing in mu, so the
answer is x(mu*) where phi(mu*) = b. Keep the function name and signature."""

PROMPT_PRODUCT = """You write numerical kernels in JAX. Task: implement `project(v, lo, hi, a, bid, b_lo, b_hi, K)`, the EXACT
Euclidean projection of v onto the PRODUCT over blocks k = 0..K-1 of {{x : lo <= x <= hi, b_lo[k] <= a_k'x <= b_hi[k]}},
where bid[i] in 0..K-1 is the block of coordinate i (blocks are disjoint, ids need not be sorted), K is a static Python
int, a has entries of EITHER sign (none zero), hi may be +inf, b_lo[k] may equal b_hi[k] (equality row), and every
block's set is non-empty. jax.jit compatible (static shapes; use jax.ops.segment_sum / segment_max / segment_min with
num_segments=K, jax.lax control flow), float64, same shape as v.
SPECIFICATION (generated by the vault's cost model, checked automatically):
  (1) exactness: max |x - x_ref| / (1 + max|x_ref|) <= 1e-9 on many small blocks, one huge block, mixed signs, infinite
      bounds, slab and equality rows, feasible inputs, unsorted ids and single-element blocks; x feasible. Feedback names
      any violated clause.
  (2) speed, measured IN THE SOLVER: on {device}, the relocated formulation of {case} (absorbed n = {n_x}) must cost at
      most {budget_us:.1f} microseconds per iteration including this operator. The starting program costs
      {current_us:.1f} microseconds per iteration there.
Useful facts: per block, phi_k(mu) = a_k'clip(v - mu a_k, lo, hi) is piecewise linear and nonincreasing in mu for any sign
pattern; the band target is clip(a_k'clip(v, lo, hi), b_lo, b_hi), so mu = 0 when it is already inside. Keep the
function name and signature."""

SETS = {
    "box_hyperplane": {"prompt": PROMPT, "cert": "opcheck.py", "plan": "single",
                       "seed_default": os.path.join(HERE, "seed_bisect.py")},
    "product_box_slab": {"prompt": PROMPT_PRODUCT, "cert": "opcheck_product.py", "plan": "product",
                         "seed_default": os.path.join(HERE, "..", "..", "..", "vault", "seeds", "seed_product.py")},
}


def evolve_operator(vault: Vault, spec: dict, device: str, iterations: int, run_root: str, llm_base: str,
                    lock: str, admit_top: int = 3) -> dict:
    ts = time.strftime("%Y%m%d_%H%M%S")
    run_dir = os.path.join(run_root, f"evolve_{ts}")
    os.makedirs(run_dir, exist_ok=True)
    S = SETS[spec.get("set", "box_hyperplane")]
    comps = [c for c in vault.components(spec.get("set", "box_hyperplane")) if c.payload.get("file")]
    seed_comp = next((c for c in comps if c.id == spec.get("replace_component")), comps[0] if comps else None)
    seed = os.path.join(run_dir, "seed.py")
    shutil.copy(seed_comp.payload["file"] if seed_comp else S["seed_default"], seed)
    prompt = S["prompt"].format(device=device, case=spec["case"], n_x=spec.get("n_x", "?"),
                                budget_us=spec["per_iteration_budget_us"],
                                current_us=spec.get("current_per_iteration_us", 0.0))
    indented = "\n".join("    " + line for line in prompt.splitlines())
    config = f"""max_iterations: {iterations}
checkpoint_interval: 5
log_level: "INFO"
random_seed: 42
max_parallel_iterations: 8
llm:
  models:
    - name: "Qwen/Qwen3.8-27B"
      weight: 1.0
  api_base: "{llm_base}"
  temperature: 1.0
  top_p: 0.95
  max_tokens: 32000
  timeout: 2400
search:
  type: "topk"
  database:
    random_seed: 42
  num_context_programs: 3
prompt:
  system_message: |
{indented}
evaluator:
  timeout: 1500
  max_retries: 1
  cascade_evaluation: false
diff_based_generation: false
max_solution_length: 20000
"""
    open(os.path.join(run_dir, "config.yaml"), "w").write(config)
    runner = f"""import json, os, sys
os.environ.setdefault("OPENAI_API_KEY", "EMPTY")
from skydiscover.api import run_discovery
res = run_discovery(evaluator="{os.path.join(HERE, 'sky_eval_v3.py')}", initial_program="{seed}",
                    config="{os.path.join(run_dir, 'config.yaml')}", output_dir="{os.path.join(run_dir, 'out')}", cleanup=False)
print("SKY_RESULT", json.dumps({{"best_score": getattr(res, "best_score", None), "metrics": getattr(res, "metrics", None)}}, default=str))
"""
    open(os.path.join(run_dir, "run.py"), "w").write(runner)
    env = dict(os.environ, SPEC_CASE=spec["case"], SPEC_FORMULATION=spec["formulation"],
               SPEC_BUDGET_PER_ITER=str(spec["per_iteration_budget_us"] * 1e-6), SPEC_LOCK=lock, OPENAI_API_KEY="EMPTY",
               CERT_SCRIPT=S["cert"], SPEC_PLAN=S["plan"])
    env.pop("LD_LIBRARY_PATH", None)
    t0 = time.time()
    with open(os.path.join(run_dir, "run.log"), "w") as log:
        subprocess.run([SKY_PY, os.path.join(run_dir, "run.py")], cwd=run_dir, env=env, stdout=log, stderr=subprocess.STDOUT)
    # admit: independent re-certification of the top programs, in-solver cost from the evaluator's metrics
    cks = sorted(glob.glob(os.path.join(run_dir, "out", "checkpoints", "checkpoint_*")), key=lambda p: int(p.rsplit("_", 1)[1]))
    admitted, rejected = [], 0
    if cks:
        progs = [json.load(open(f)) for f in glob.glob(os.path.join(cks[-1], "programs", "*.json"))]
        progs.sort(key=lambda p: -p["metrics"].get("combined_score", 0))
        for rank, p in enumerate(progs[:admit_top]):
            path = os.path.join(os.path.dirname(vault.path), "components", f"agent_{ts}_top{rank}.py")
            os.makedirs(os.path.dirname(path), exist_ok=True)
            open(path, "w").write(p["solution"])
            env2 = dict(os.environ, OPCHECK_NO_TIMING="1")
            env2.pop("LD_LIBRARY_PATH", None)
            out = subprocess.run([PY, os.path.join(HERE, S["cert"]), path], capture_output=True, text=True, env=env2)
            cert = json.loads([l for l in out.stdout.splitlines() if l.startswith("{")][-1])
            if cert.get("certified") != 1.0:
                rejected += 1
                continue
            per_iter_us = p["metrics"].get("per_iter_us", 0.0)
            e = vault.add("component", {
                "set": spec.get("set", "box_hyperplane"), "file": path, "contract": f"{S['cert']} clauses",
                "certificate": {k: cert.get(k) for k in ("certified", "max_err", "failing_clauses")},
                "calibration": {device: {"per_iteration_us_in_solver": per_iter_us, "case": spec["case"]}},
                "transfer": [], "loses": []},
                id=f"component:agent_{ts}_top{rank}",
                provenance={"origin": "agent evolve_operator", "spec": spec, "run_dir": run_dir,
                            "iteration_found": p.get("iteration_found"), "score": p["metrics"].get("combined_score")})
            admitted.append({"id": e.id, "per_iter_us": per_iter_us,
                             "meets": per_iter_us > 0 and per_iter_us <= spec["per_iteration_budget_us"]})
    return {"run_dir": run_dir, "wall_s": time.time() - t0, "admitted": admitted, "rejected_uncertified": rejected,
            "spec_met": any(a["meets"] for a in admitted)}
